# Generated by Django 5.2 on 2025-05-05 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(default='patient', max_length=255),
        ),
    ]
