# Generated by Django 4.2.20 on 2025-05-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='patient', max_length=255),
        ),
    ]
