# Generated by Django 4.2.20 on 2025-05-02 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0003_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='clinic_app.user'),
        ),
    ]
