# Generated by Django 4.2.20 on 2025-05-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0004_user_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allergy_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='chronic_disease',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='dialysis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='drug_allergy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='id_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='social_status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='takes_medications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='treatment_plan',
            field=models.TextField(blank=True),
        ),
    ]
