# Generated by Django 4.2.20 on 2025-05-02 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0005_user_allergy_details_user_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dialysis',
            field=models.TextField(blank=True),
        ),
    ]
