# Generated by Django 4.2.20 on 2025-05-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0007_alter_user_dialysis_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(default='admin', max_length=255),
        ),
    ]
