# Generated by Django 4.2.20 on 2025-05-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0008_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(default='patient', max_length=255),
        ),
    ]
