# Generated by Django 4.2.20 on 2025-05-04 17:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0009_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='end_at',
        ),
        migrations.AddField(
            model_name='appointment',
            name='end_at_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='appointment',
            name='end_at_time',
            field=models.TimeField(default=datetime.time(9, 30)),
        ),
        migrations.AddField(
            model_name='appointment',
            name='start_at_time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='start_at_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
