# Generated by Django 5.2 on 2025-05-04 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0010_remove_appointment_end_at_appointment_end_at_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='end_at_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='end_at_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='start_at_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='start_at_time',
            field=models.TimeField(),
        ),
    ]
