# Generated by Django 4.2.20 on 2025-05-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0011_alter_appointment_end_at_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(default='patient', max_length=255),
        ),
    ]
